// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh_ox2PSqj_zfk1xXDW5ztkj_PW0vEoWc',
    appId: '1:279470076021:web:060786e62720893457083c',
    messagingSenderId: '279470076021',
    projectId: 'horyx-bfd5a',
    authDomain: 'horyx-bfd5a.firebaseapp.com',
    storageBucket: 'horyx-bfd5a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdLEFGZDbwqTs6vPXf_SMgrG97WnPkFsM',
    appId: '1:279470076021:android:e4025cf59f8e2e9b57083c',
    messagingSenderId: '279470076021',
    projectId: 'horyx-bfd5a',
    storageBucket: 'horyx-bfd5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQVywOwqQ6ddV5-pMNkbJxXl3M7GhXzmE',
    appId: '1:279470076021:ios:05234d3341e0626457083c',
    messagingSenderId: '279470076021',
    projectId: 'horyx-bfd5a',
    storageBucket: 'horyx-bfd5a.firebasestorage.app',
    iosBundleId: 'com.example.horyxFluter',
  );
}
